### ISSUE TITLE
git-attr-check: Symbol’s function definition is void: caddr

### ISSUE THREAD

**Issue by matthewbauer** [arnested/git-attr#1]
Hi,

This package works well for me but it looks like you are missing this:

```
(require 'cl-lib)
```

at the header

**Comment by arnested** [comment]
Sorry for not responding to this earlier, @matthewbauer.

`caddr` is defined in `subr.el` but I just notived they used to be defined in `cl-lib` previously (before Emacs 26, I think). The same goes for `cdddr`.

Instead of requiring `cl-lib` (which is not needed on Emacs 26) I'll expand the functions inline instead. See 3e43a0cf616b00a4bbd3c6b49fd2397f3103796f.
